{
  imports = [
    ./hardware-configuration.nix
    ../../modules/base.nix
    ../../modules/boot.nix
    ../../modules/disko.nix
    ../../modules/impermanence.nix
    ../../modules/storage-maintenance.nix
    ../../modules/desktop-environment.nix
    ../../modules/desktop-apps.nix
    ../../modules/development.nix
    ../../modules/gaming.nix
    ../../modules/virtualisation.nix
    ../../modules/nvidia.nix
    ../../modules/nixos-update-checker.nix
    ./features/audient-evo4.nix
    ./features/gpu-passthrough
    ./features/local-ai
    ./features/restic-backup.nix
    ./features/sunshine
    ./features/vpn-vm-network.nix
    ./secondary-drives.nix
  ];
}
